// Ghana Regions and MMDAs data

// All 16 regions of Ghana
export const ghanaRegions = [
  'Ahafo',
  'Ashanti',
  'Bono',
  'Bono East',
  'Central',
  'Eastern',
  'Greater Accra',
  'North East',
  'Northern',
  'Oti',
  'Savannah',
  'Upper East',
  'Upper West',
  'Volta',
  'Western',
  'Western North'
];

// Sample MMDAs for each region (not exhaustive)
export const mmdaByRegion: Record<string, string[]> = {
  'Ahafo': [
    'Asunafo North Municipal',
    'Asunafo South District',
    'Asutifi North District',
    'Asutifi South District',
    'Tano North Municipal',
    'Tano South Municipal'
  ],
  'Ashanti': [
    'Kumasi Metropolitan',
    'Asante Akim Central Municipal',
    'Asante Akim North District',
    'Asante Akim South Municipal',
    'Adansi North District',
    'Adansi South District',
    'Amansie Central District',
    'Amansie West District',
    'Atwima Kwanwoma District',
    'Atwima Mponua District',
    'Atwima Nwabiagya Municipal',
    'Bekwai Municipal',
    'Bosome Freho District',
    'Bosomtwe District',
    'Ejisu Municipal',
    'Ejura Sekyedumase Municipal',
    'Juaben Municipal',
    'Kwabre East Municipal',
    'Mampong Municipal',
    'Obuasi East District',
    'Obuasi Municipal',
    'Offinso Municipal',
    'Offinso North District',
    'Sekyere Afram Plains District',
    'Sekyere Central District',
    'Sekyere East District',
    'Sekyere Kumawu District',
    'Sekyere South District'
  ],
  'Bono': [
    'Sunyani Municipal',
    'Sunyani West District',
    'Berekum East Municipal',
    'Berekum West District',
    'Dormaa Central Municipal',
    'Dormaa East District',
    'Dormaa West District',
    'Jaman North District',
    'Jaman South Municipal',
    'Tain District',
    'Wenchi Municipal'
  ],
  'Bono East': [
    'Techiman Municipal',
    'Techiman North District',
    'Atebubu-Amantin Municipal',
    'Kintampo North Municipal',
    'Kintampo South District',
    'Nkoranza North District',
    'Nkoranza South Municipal',
    'Pru East District',
    'Pru West District',
    'Sene East District',
    'Sene West District'
  ],
  'Central': [
    'Cape Coast Metropolitan',
    'Abura Asebu Kwamankese District',
    'Agona East District',
    'Agona West Municipal',
    'Ajumako Enyan Essiam District',
    'Asikuma Odoben Brakwa District',
    'Assin Central Municipal',
    'Assin North District',
    'Assin South District',
    'Awutu Senya District',
    'Awutu Senya East Municipal',
    'Effutu Municipal',
    'Ekumfi District',
    'Gomoa Central District',
    'Gomoa East District',
    'Gomoa West District',
    'Komenda Edina Eguafo Abirem Municipal',
    'Mfantseman Municipal',
    'Twifo Atti Morkwa District',
    'Twifo Hemang Lower Denkyira District',
    'Upper Denkyira East Municipal',
    'Upper Denkyira West District'
  ],
  'Eastern': [
    'Koforidua Municipal',
    'Abuakwa North Municipal',
    'Abuakwa South Municipal',
    'Achiase District',
    'Akuapem North Municipal',
    'Akuapem South District',
    'Akyemansa District',
    'Asene Manso Akroso District',
    'Asuogyaman District',
    'Atiwa East District',
    'Atiwa West District',
    'Ayensuano District',
    'Birim Central Municipal',
    'Birim North District',
    'Birim South District',
    'Denkyembour District',
    'Fanteakwa North District',
    'Fanteakwa South District',
    'Kwaebibirem Municipal',
    'Kwahu Afram Plains North District',
    'Kwahu Afram Plains South District',
    'Kwahu East District',
    'Kwahu South District',
    'Kwahu West Municipal',
    'Lower Manya Krobo Municipal',
    'New Juaben North Municipal',
    'New Juaben South Municipal',
    'Nsawam Adoagyiri Municipal',
    'Okere District',
    'Suhum Municipal',
    'Upper Manya Krobo District',
    'Upper West Akim District',
    'West Akim Municipal',
    'Yilo Krobo Municipal'
  ],
  'Greater Accra': [
    'Accra Metropolitan',
    'Ada East District',
    'Ada West District',
    'Adentan Municipal',
    'Ashaiman Municipal',
    'Ayawaso Central Municipal',
    'Ayawaso East Municipal',
    'Ayawaso North Municipal',
    'Ayawaso West Municipal',
    'Ga Central Municipal',
    'Ga East Municipal',
    'Ga North Municipal',
    'Ga South Municipal',
    'Ga West Municipal',
    'Korle Klottey Municipal',
    'Kpone Katamanso Municipal',
    'Krowor Municipal',
    'La Dade Kotopon Municipal',
    'La Nkwantanang Madina Municipal',
    'Ledzokuku Municipal',
    'Ningo Prampram District',
    'Okaikwei North Municipal',
    'Okaikwei South Municipal',
    'Shai Osudoku District',
    'Tema Metropolitan',
    'Tema West Municipal',
    'Weija Gbawe Municipal'
  ],
  'North East': [
    'Chereponi District',
    'East Mamprusi Municipal',
    'Mamprugu Moagduri District',
    'West Mamprusi Municipal',
    'Yunyoo-Nasuan District'
  ],
  'Northern': [
    'Tamale Metropolitan',
    'Gushegu Municipal',
    'Karaga District',
    'Kpandai District',
    'Kumbungu District',
    'Mion District',
    'Nanton District',
    'Nanumba North Municipal',
    'Nanumba South District',
    'Saboba District',
    'Sagnarigu Municipal',
    'Savelugu Municipal',
    'Tamale North Sub Metro',
    'Tamale South Sub Metro',
    'Tatale Sangule District',
    'Tolon District',
    'Yendi Municipal',
    'Zabzugu District'
  ],
  'Oti': [
    'Biakoye District',
    'Jasikan District',
    'Kadjebi District',
    'Krachi East Municipal',
    'Krachi Nchumuru District',
    'Krachi West District',
    'Nkwanta North District',
    'Nkwanta South Municipal'
  ],
  'Savannah': [
    'Central Gonja District',
    'East Gonja Municipal',
    'North East Gonja District',
    'North Gonja District',
    'Sawla-Tuna-Kalba District',
    'West Gonja District',
    'Bole District'
  ],
  'Upper East': [
    'Bolgatanga Municipal',
    'Bawku Municipal',
    'Bawku West District',
    'Binduri District',
    'Bongo District',
    'Builsa North Municipal',
    'Builsa South District',
    'Garu District',
    'Kassena Nankana Municipal',
    'Kassena Nankana West District',
    'Nabdam District',
    'Pusiga District',
    'Talensi District',
    'Tempane District'
  ],
  'Upper West': [
    'Wa Municipal',
    'Daffiama Bussie Issa District',
    'Jirapa Municipal',
    'Lambussie Karni District',
    'Lawra Municipal',
    'Nadowli Kaleo District',
    'Nandom District',
    'Sissala East Municipal',
    'Sissala West District',
    'Wa East District',
    'Wa West District'
  ],
  'Volta': [
    'Ho Municipal',
    'Adaklu District',
    'Afadzato South District',
    'Agotime Ziope District',
    'Akatsi North District',
    'Akatsi South District',
    'Central Tongu District',
    'Ho West District',
    'Hohoe Municipal',
    'Keta Municipal',
    'Ketu North Municipal',
    'Ketu South Municipal',
    'North Dayi District',
    'North Tongu District',
    'South Dayi District',
    'South Tongu District'
  ],
  'Western': [
    'Sekondi-Takoradi Metropolitan',
    'Ahanta West Municipal',
    'Effia Kwesimintsim Municipal',
    'Ellembelle District',
    'Jomoro Municipal',
    'Mpohor District',
    'Nzema East Municipal',
    'Prestea Huni Valley Municipal',
    'Shama District',
    'Tarkwa Nsuaem Municipal',
    'Wassa Amenfi Central District',
    'Wassa Amenfi East Municipal',
    'Wassa Amenfi West Municipal',
    'Wassa East District'
  ],
  'Western North': [
    'Aowin Municipal',
    'Bia East District',
    'Bia West District',
    'Bibiani Anhwiaso Bekwai Municipal',
    'Bodi District',
    'Juaboso District',
    'Sefwi Akontombra District',
    'Sefwi Wiawso Municipal',
    'Suaman District'
  ]
};

// Total count of MMDAs in Ghana
export const getTotalMMDAs = (): number => {
  return Object.values(mmdaByRegion).reduce((total, mmdas) => total + mmdas.length, 0);
};